const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8080/api/v1").replace(/\/+$/, "");
const API_TIMEOUT_MS = 8000;
type JsonObject = Record<string, unknown>;
export type Direction = "rise" | "fall" | "mixed" | "neutral";
export type ProjectType = "Airport" | "Road corridor" | "Transit" | "Industrial" | "IT corridor";
export type InfrastructureRecord = { id: string; regionId: string; name: string; type: ProjectType; status: string; openingYear: number | null; latitude: number; longitude: number; contribution: [number, number]; confidence: number; emoji: string; summary: string; sourceUrl?: string };
export type Driver = { id: string; name: string; type: ProjectType; status: string; contribution: [number, number]; confidence: number; timeline: string; summary: string; image?: string; sourceCount: number; x: number; y: number };
export type Region = { id: string; name: string; state: string; district: string; value: number; unit: string; projected: [number, number] | null; direction: Direction; confidence: number | null; x: number; y: number; size: number; color: string; drivers: Driver[] };
export type DbGeometryRegion = { id: string; name: string; district: string; slug: string; points: string; path: Array<{ lat: number; lng: number }>; centroid: [number, number] };
export type PredictionInput = { regionId: string; currentValue: number; propertyType: string; horizonMonths: number };
export type PredictionResult = { low: number; high: number; horizonMonths: number; propertyType: string; methodology: string };
export type EvidenceRecord = { id: string; driverId: string; title: string; publisher: string; publishedAt: string; url?: string };
export type LatestNewsRecord = EvidenceRecord & { regionId?: string };
export type GroundTruthSnapshot = { states: string[]; updatedAt: string; evidenceWindow: string; regions: Region[]; projectTypes: ProjectType[]; officialValueUrl: string };
type RegionApi = { id: string; name: string; state?: string; district?: string; geometry?: JsonObject; baseValue?: number; baseValueUnit?: string; projectedValueLow?: number; projectedValueHigh?: number; confidenceScore?: number; drivers?: Driver[] };
type InfrastructureApi = { id: string; regionId: string; name: string; type: ProjectType; status: string; openingYear?: number; latitude: number; longitude: number; contributionLow?: number; contributionHigh?: number; confidence?: number; emoji?: string; summary?: string; sourceUrl?: string };
function object(value: unknown): JsonObject { return value !== null && typeof value === "object" ? value as JsonObject : {}; }
function number(value: unknown, fallback = 0): number { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function string(value: unknown, fallback = ""): string { return typeof value === "string" && value.trim() ? value : fallback; }
function query(params: Record<string, string | undefined>) { const search = new URLSearchParams(); Object.entries(params).forEach(([key, value]) => { if (value) search.set(key, value); }); const result = search.toString(); return result ? `?${result}` : ""; }
function arrayCoordinates(geometry: JsonObject): Array<[number, number]> { const coordinates = geometry.coordinates; if (!Array.isArray(coordinates)) return []; const polygon = Array.isArray(coordinates[0]) && Array.isArray(coordinates[0][0]) ? coordinates[0] : coordinates; return (polygon as unknown[]).flatMap((point) => Array.isArray(point) && point.length >= 2 ? [[number(point[1]), number(point[0])] as [number, number]] : []); }
function toRegion(raw: RegionApi): Region { const projected = raw.projectedValueLow != null && raw.projectedValueHigh != null ? [number(raw.projectedValueLow), number(raw.projectedValueHigh)] as [number, number] : null; const value = number(raw.baseValue); const direction: Direction = projected ? projected[0] >= value ? "rise" : projected[1] < value ? "fall" : "mixed" : "neutral"; return { id: raw.id, name: raw.name, state: string(raw.state), district: string(raw.district), value, unit: string(raw.baseValueUnit, "per sq yd"), projected, direction, confidence: raw.confidenceScore == null ? null : number(raw.confidenceScore), x: 50, y: 50, size: 12, color: "#c7c3b8", drivers: Array.isArray(raw.drivers) ? raw.drivers : [] }; }
function toGeometry(raw: RegionApi): DbGeometryRegion | null { const points = arrayCoordinates(object(raw.geometry)); if (!points.length) return null; return { id: raw.id, name: raw.name, district: string(raw.district), slug: raw.id, points: points.map(([lat, lng]) => `${lat},${lng}`).join(" "), path: points.map(([lat, lng]) => ({ lat, lng })), centroid: points.reduce(([lat, lng], [nextLat, nextLng]) => [lat + nextLat / points.length, lng + nextLng / points.length], [0, 0] as [number, number]) }; }
async function request<T>(path: string, init?: RequestInit): Promise<T> { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), API_TIMEOUT_MS); try { const response = await fetch(`${API_BASE_URL}${path}`, { ...init, signal: controller.signal, headers: { Accept: "application/json", "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) throw new Error(`Ground Truth API ${response.status}`); return await response.json() as T; } finally { window.clearTimeout(timeout); } }
export async function getAvailableStates(): Promise<string[]> { return request<string[]>("/regions/states"); }
export async function getGroundTruthSnapshot(state: string): Promise<GroundTruthSnapshot> { const rows = await request<RegionApi[]>(`/regions${query({ state })}`); return { states: state ? [state] : [], updatedAt: new Date().toISOString(), evidenceWindow: "Last 90 days", regions: rows.map(toRegion), projectTypes: ["Airport", "Road corridor", "Transit", "Industrial", "IT corridor"], officialValueUrl: "https://bhubharati.telangana.gov.in/viewMarketValueLandStampDuty" }; }
export async function getRegionGeometries(state: string): Promise<DbGeometryRegion[]> { const rows = await request<RegionApi[]>(`/regions${query({ state })}`); return rows.map(toGeometry).filter((row): row is DbGeometryRegion => Boolean(row)); }
export async function getRegions(state?: string): Promise<Region[]> { return (await getGroundTruthSnapshot(state ?? "")).regions; }
export async function getRegionById(regionId: string): Promise<Region | undefined> { const rows = await getRegions(); return rows.find((item) => item.id === regionId); }
export async function getInfrastructureRecords(state: string): Promise<InfrastructureRecord[]> { const records = await request<InfrastructureApi[]>(`/infrastructure${query({ state })}`); return records.map((record) => ({ id: record.id, regionId: record.regionId, name: record.name, type: record.type, status: record.status, openingYear: record.openingYear ?? null, latitude: number(record.latitude), longitude: number(record.longitude), contribution: [number(record.contributionLow), number(record.contributionHigh)] as [number, number], confidence: number(record.confidence), emoji: string(record.emoji, "📍"), summary: string(record.summary), sourceUrl: record.sourceUrl })); }
export async function getInfrastructureDrivers(regionId?: string, projectTypes?: ProjectType[]): Promise<Driver[]> { const regions = await getRegions(); return regions.filter((region) => !regionId || region.id === regionId).flatMap((region) => region.drivers).filter((driver) => !projectTypes?.length || projectTypes.includes(driver.type)); }
export async function getEvidence(regionId: string): Promise<EvidenceRecord[]> { const records = await request<Array<{ id: string; title: string; source: string; publishedDate: string; url?: string }>>(`/regions/${encodeURIComponent(regionId)}/news?page=0&size=20`); return records.map((record) => ({ id: record.id, driverId: "", title: record.title, publisher: record.source, publishedAt: record.publishedDate, url: record.url })); }
export async function getLatestNews(): Promise<LatestNewsRecord[]> { const records = await request<Array<{ id: string; title: string; source: string; publishedDate: string; url?: string; regionId?: string }>>("/news/latest?page=0&size=20"); return records.map((record) => ({ id: record.id, driverId: "", title: record.title, publisher: record.source, publishedAt: record.publishedDate, url: record.url, regionId: record.regionId })); }
export async function predictFutureValue(input: PredictionInput): Promise<PredictionResult> { return request<PredictionResult>("/predictions", { method: "POST", body: JSON.stringify(input) }); }
export async function getOfficialValueUrl(): Promise<string> { return "https://bhubharati.telangana.gov.in/viewMarketValueLandStampDuty"; }
